### ISSUE TITLE
Can't tell who added a quote without doing !quote

### ISSUE THREAD

**Issue by ghost** [bitfolk/enoch#1]
It's been pointed out that it's annoying when you go to rate a quote and it doesn't let you because you are the one who added the quote. When a quote pops up as a timed quote (e.g. 60 minute quote) it currently doesn't say who added it. If it did say that you added it then you'd know not to bother trying to rate it.

**Comment by pidg** [comment]
I disagree that this is annoying. Trying to rate your own quote (and failing) still acts as an encouragement to others to rate your quote.

**Comment by bitfolk** [comment]
The reason why I didn't include extra info like who added the quote or when it was added to the timed quotes is that this information uses some of the space available on the line, and might result in long quotes being truncated.

Most quotes are quite short though compared to the maximum IRC line length (512?). What we could do is check if all the info will fit, and include it if so. If the quote will be truncated then we could miss off all the additional info except the quote ID.

I do not want the bot to be saying more than one line each time it does a quote. I think that will be irritating to quite a lot of people.

**Comment by bitfolk** [comment]
I've added the nick of the person who added the quote to the timed and on-join quotes, if there is space.
